import type { Product, AuditItem, FinancialMetrics, RiskLog } from "@/types";

// Mock data for development
export const mockProducts: Product[] = [
  {
    id: "1",
    titleZh: "适用于 iPhone 15 的透明手机壳",
    titleTh: "เคสใสสำหรับ iPhone 15",
    sourcePlatform: "1688",
    sourceItemId: "123456789",
    priceCny: 15,
    priceThb: 89,
    profitMargin: 25.3,
    riskStatus: "pass",
    status: "listed",
    createdAt: "2026-07-03T10:00:00Z",
  },
  {
    id: "2",
    titleZh: "USB-C 快充数据线 1米",
    titleTh: "สายชาร์จ USB-C เร็ว 1 เมตร",
    sourcePlatform: "pdd",
    sourceItemId: "987654321",
    priceCny: 8,
    priceThb: 49,
    profitMargin: 18.7,
    riskStatus: "pass",
    status: "auditing",
    createdAt: "2026-07-03T14:30:00Z",
  },
  {
    id: "3",
    titleZh: "无线蓝牙耳机 降噪版",
    titleTh: "หูฟังบลูทูธไร้สาย ตัดเสียงรบกวน",
    sourcePlatform: "1688",
    sourceItemId: "456789123",
    priceCny: 120,
    priceThb: 599,
    profitMargin: 12.1,
    riskStatus: "block",
    status: "blocked",
    createdAt: "2026-07-04T09:15:00Z",
  },
  {
    id: "4",
    titleZh: "硅胶手机支架 车载",
    titleTh: "ที่ยึดโทรศัพท์ในรถ ซิลิโคน",
    sourcePlatform: "pdd",
    sourceItemId: "789123456",
    priceCny: 5,
    priceThb: 35,
    profitMargin: 32.5,
    riskStatus: "pass",
    status: "auditing",
    createdAt: "2026-07-04T11:00:00Z",
  },
  {
    id: "5",
    titleZh: "LED 台灯 护眼学习灯",
    titleTh: "โคมไฟ LED เรียนรู้ ถนอมสายตา",
    sourcePlatform: "1688",
    sourceItemId: "321654987",
    priceCny: 85,
    priceThb: 450,
    profitMargin: 21.8,
    riskStatus: "pass",
    status: "pending",
    createdAt: "2026-07-04T15:45:00Z",
  },
];

export const mockAudits: AuditItem[] = [
  {
    id: "1",
    productId: "2",
    titleZh: "USB-C 快充数据线 1米",
    titleTh: "สายชาร์จ USB-C เร็ว 1 เมตร",
    descriptionTh: "สายชาร์จคุณภาพสูง รองรับ fast charging...",
    profitMargin: 18.7,
    confidenceScore: 0.92,
    riskFlag: false,
    status: "pending",
    createdAt: "2026-07-03T14:30:00Z",
  },
  {
    id: "2",
    productId: "4",
    titleZh: "硅胶手机支架 车载",
    titleTh: "ที่ยึดโทรศัพท์ในรถ ซิลิโคน",
    descriptionTh: "ที่ยึดโทรศัพท์แบบซิลิโคน ติดตั้งง่าย...",
    profitMargin: 32.5,
    confidenceScore: 0.88,
    riskFlag: false,
    status: "pending",
    createdAt: "2026-07-04T11:00:00Z",
  },
  {
    id: "3",
    productId: "5",
    titleZh: "LED 台灯 护眼学习灯",
    titleTh: "โคมไฟ LED เรียนรู้ ถนอมสายตา",
    descriptionTh: "โคมไฟ LED สำหรับการศึกษา ถนอมดวงตา...",
    profitMargin: 21.8,
    confidenceScore: 0.76,
    riskFlag: true,
    riskReason: "翻译置信度低于85%",
    status: "pending",
    createdAt: "2026-07-04T15:45:00Z",
  },
];

export const mockFinancialMetrics: FinancialMetrics = {
  totalSales: 125400,
  totalProfit: 29500,
  avgProfitMargin: 23.5,
  profitDeviation: -1.2,
};

export const mockRiskLogs: RiskLog[] = [
  {
    id: "1",
    productId: "3",
    productTitle: "无线蓝牙耳机 降噪版",
    riskType: "profit",
    riskDetail: "利润率 12.1% 低于阈值 15%",
    actionTaken: "自动拦截，标记利润不足",
    createdAt: "2026-07-04T09:15:00Z",
  },
  {
    id: "2",
    productId: "6",
    productTitle: "运动手环 Pro",
    riskType: "brand",
    riskDetail: "检测到品牌词: Nike",
    actionTaken: "自动拦截，标记品牌侵权",
    createdAt: "2026-07-04T08:30:00Z",
  },
  {
    id: "3",
    productId: "7",
    productTitle: "儿童玩具套装",
    riskType: "category",
    riskDetail: "类目错放: 应归入玩具类",
    actionTaken: "标记待人工审核",
    createdAt: "2026-07-03T16:20:00Z",
  },
];
